In [4]:
import networkx as nx
import numpy as np

def graph_to_adjacency_matrix(G):
    # 检查图中是否有重复的边
    assert len(G.edges()) == len(set(G.edges())), "图中存在重复的边"
    #这里的set具有集合上的意义。也就是说它不能存在重复的

    # 获取图中的节点数量
    n = len(G.nodes())
    # 创建一个n*n的零矩阵
    matrix = np.zeros((n, n), dtype=int)

    # 遍历图中的每条边
    for u, v in G.edges():
        if u != v:  # 排除自环
            # 因为要创建上对角矩阵，所以只填充上三角部分
            matrix[min(u, v), max(u, v)] = 1

    return matrix

# 示例使用
G = nx.Graph()
G.add_edges_from([(0, 1), (0, 2), (1, 2), (2, 3),(3,1), (1,3)])

matrix = to_upper_triangular_adjacency_matrix(G)
print(matrix)

[[0 1 1 0]
 [0 0 1 1]
 [0 0 0 1]
 [0 0 0 0]]
